name: Container Apps Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3   
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
        
    - name: Install az containerapp extension
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

     # Go image build and push   
    - name: Build Docker Go image
      run: |
        docker build --platform linux --tag aminespinoza/goservice:latest -f src/go/Dockerfile .
    - name: Publish Docker Go image
      run: |
        docker push aminespinoza/goservice:latest
    - name: Deploy Go container App
      run: |
        az containerapp up --name go-container-app --image aminespinoza/goservice:latest --resource-group playingGroup --environment general-container-env --ingress external --target-port 8081


