name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3   
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
     # Python image build and push   
    - name: Build Docker Python image
      run: | 
        docker build --platform linux --tag aminespinoza/pythonservice:latest -f src/python/Dockerfile .
    - name: Publish Docker Python image
      run: |
        docker push aminespinoza/pythonservice:latest
    
    

     # Go image build and push   
    #- name: Build Docker Go image
    #  run: |
    #    docker build --platform linux --tag aminespinoza/goservice:latest -f src/go/Dockerfile .
    #- name: Publish Docker Go image
    #  run: |
    #    docker push aminespinoza/goservice:latest
        
      # NET image build and push
    #- name: Build Docker NET image
    #  run: | 
    #    docker build --platform linux --tag aminespinoza/netservice:latest -f src/net/Dockerfile .
    #- name: Publish Docker NET image
    #  run: |
    #    docker push aminespinoza/netservice:latest
    - name: Install az containerapp extension
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt
        
    - name: Deploy Python container App
      run: |
        az containerapp up --name go-container-app --image aminespinoza/pythonservice:latest --resource-group playingGroup --environment go-container-app-env --ingress external 
