name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3   
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker Python image
      run: | 
        docker build --platform linux --tag aminespinoza/pythonservice:latest -f src/python/Dockerfile .
    - name: Publish Docker image
      run: |
        docker push aminespinoza/pythonservice:latest
    - name: Build Docker Go image
      run: |
        docker build --platform linux --tag aminespinoza/goservice:latest -f src/go/Dockerfile .
